layout_spectrum: 0.15095089026726782
typography_spectrum: 0.4567130389623344
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.5375302203465253
  lightness: 0.6358085535466671
  saturation: 0.6799775820691139
  rhythmicContrast: 0.16774208866991103
name: ServiceSheets
favicon: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
